"""Correction noms de table pour clés étrangères

Revision ID: 08bcb2ad25c4
Revises: f25a62bf8b7c
Create Date: 2025-06-24 20:33:41.593861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bcb2ad25c4'
down_revision = 'f25a62bf8b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=100), nullable=False),
    sa.Column('recette', sa.Float(), nullable=True),
    sa.Column('frais', sa.Float(), nullable=True),
    sa.Column('paye', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musiciens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cachets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musicien_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('nombre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['musicien_id'], ['musiciens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musicien_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('motif', sa.String(length=100), nullable=True),
    sa.Column('precision', sa.String(length=255), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('brut', sa.Float(), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=True),
    sa.Column('auto_cb_asso7', sa.Boolean(), nullable=False),
    sa.Column('operation_liee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ),
    sa.ForeignKeyConstraint(['musicien_id'], ['musiciens.id'], ),
    sa.ForeignKeyConstraint(['operation_liee_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('musicien_id', sa.Integer(), nullable=False),
    sa.Column('paye', sa.Boolean(), nullable=True),
    sa.Column('credit_calcule', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ),
    sa.ForeignKeyConstraint(['musicien_id'], ['musiciens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musicien_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['musicien_id'], ['musiciens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('report')
    op.drop_table('operation')
    op.drop_table('cachet')
    op.execute("DROP TABLE IF EXISTS concert CASCADE")
    op.execute("DROP TABLE IF EXISTS musicien CASCADE")
    op.drop_table('participation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('concert_id', sa.INTEGER(), nullable=False),
    sa.Column('musicien_id', sa.INTEGER(), nullable=False),
    sa.Column('credit_calcule', sa.FLOAT(), nullable=True),
    sa.Column('paye', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.ForeignKeyConstraint(['musicien_id'], ['musicien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_musicien',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('actif', sa.BOOLEAN(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musicien',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('actif', sa.BOOLEAN(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('lieu', sa.VARCHAR(length=100), nullable=False),
    sa.Column('recette', sa.FLOAT(), nullable=True),
    sa.Column('frais', sa.FLOAT(), nullable=True),
    sa.Column('paye', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cachet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('musicien_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('montant', sa.FLOAT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('declarant', sa.VARCHAR(length=100), nullable=True),
    sa.Column('saisie_timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['musicien_id'], ['musicien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('musicien_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('motif', sa.VARCHAR(length=100), nullable=True),
    sa.Column('precision', sa.VARCHAR(length=255), nullable=True),
    sa.Column('montant', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('brut', sa.FLOAT(), nullable=True),
    sa.Column('concert_id', sa.INTEGER(), nullable=True),
    sa.Column('auto_cb_asso7', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('operation_liee_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.ForeignKeyConstraint(['musicien_id'], ['musicien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('musicien_id', sa.INTEGER(), nullable=False),
    sa.Column('montant', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['musicien_id'], ['musicien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reports')
    op.drop_table('participations')
    op.drop_table('operations')
    op.drop_table('cachets')
    op.execute("DROP TABLE IF EXISTS musicien CASCADE")
    op.execute("DROP TABLE IF EXISTS concert CASCADE")
    # ### end Alembic commands ###
