"""Initialisation BDD musiciens

Revision ID: 5b880b705a2f
Revises: 
Create Date: 2025-06-17 09:35:34.765105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b880b705a2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=100), nullable=False),
    sa.Column('recette', sa.Float(), nullable=True),
    sa.Column('frais', sa.Float(), nullable=True),
    sa.Column('paye', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musicien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cachet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musicien_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('declarant', sa.String(length=100), nullable=True),
    sa.Column('saisie_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['musicien_id'], ['musicien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musicien_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('motif', sa.String(length=100), nullable=True),
    sa.Column('precision', sa.String(length=255), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('brut', sa.Float(), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.ForeignKeyConstraint(['musicien_id'], ['musicien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('musicien_id', sa.Integer(), nullable=False),
    sa.Column('credit_calcule', sa.Float(), nullable=True),
    sa.Column('paye', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.ForeignKeyConstraint(['musicien_id'], ['musicien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musicien_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['musicien_id'], ['musicien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('participation')
    op.drop_table('operation')
    op.drop_table('cachet')
    op.drop_table('musicien')
    op.drop_table('concert')
    # ### end Alembic commands ###
