"""Ajout du champ type à Musicien

Revision ID: f72685bc927f
Revises: c10172e83bd7
Create Date: 2025-06-17 11:53:03.890505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72685bc927f'
down_revision = 'c10172e83bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musicien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musicien', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
